services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasklib_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - tasklib

  db:
    image: mysql:8.0
    container_name: tasklib_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasklib
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tasklib

  nginx:
    image: nginx:stable-alpine
    container_name: tasklib_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tasklib
      
  node:
    image: node:20-alpine
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - app
    networks:
      - tasklib

volumes:
  db_data:

networks:
  tasklib:
    driver: bridge

